### ISSUE TITLE
Large domains necessitates running FRE tools as separate PBS job

### ISSUE THREAD

**Issue by ashjbarnes** [COSIMA/mom6-regional#18]
Currently the demo notebook works fine for 'small' domains. Anything over a big area irrespective of resolution requires the MakeTopogParallel F90 script to stall trying to deal with too big an array with just one core

Workaround currently is to

1. Run expt.bathymetry
2. Oh crap my domain was too big. Restart notebook
3. Navigate to your input directory in a terminal, run an interactive job with X number of cores. Call MakeTopogParallel on the grid.nc file that Python made for you before the pipeline failed at the F90 script
4. Run expt.bathymetry again but this time pass 'maketopog = False' to stop it trying to run MakeTopogParallel. This finishes the job

Two options to resolve: Either regrid the bathymetry onto hgrid & handle metadata in python OR incorporate an automatic 'run MakeTopogParallel as PBS job' into pipeline. 

I'm in favour of the former because it should be more environment agnostic.

**Comment by navidcy** [comment]
The former sounds better. Then this can be part of a potential python package.

**Comment by ashjbarnes** [comment]
this issue is irrelevant now since we've switched to Python, but the python / ESMF implementation still needs testing on large domains.
