### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by navidcy** [COSIMA/mom6-regional#28]
@angus-g would you recommend sphinx or read-the-docs? Or something else?

**Comment by navidcy** [comment]
After we sort #26 could you set up a placeholder documentation @angus-g? Without content, just automatically populate the docstrings. 

Is there a way to use markdown files instead of rst?

**Comment by angus-g** [comment]
Yep can do.

> Is there a way to use markdown files instead of rst?

Yep, I'll set it up for that!

**Comment by navidcy** [comment]
#38 dealt with that! this is a great start!!

**Comment by navidcy** [comment]
@angus-g how can somebody build the docs locally?

**Comment by angus-g** [comment]
If you install sphinx and `pip install -r docs/requirements.txt`, you should be able to run `make html` in the `docs` dir to generate something.

**Comment by navidcy** [comment]
Oh I just saw this! I figured out a way to do it with conda  and made a PR (see #44). I'll add this way there also!
