### ISSUE TITLE
North Sea domain resulted in masking ocean instead of land

### ISSUE THREAD

**Issue by navidcy** [COSIMA/mom6-regional#29]
cc @wghuneke

**Comment by wghuneke** [comment]
Domain: 
yextent = [50,65] ## latitude
xextent = [0,15] ## longitude

<img width="585" alt="Screenshot_NorthSea_LandOcean" src="https://github.com/COSIMA/mom6-regional-scripts/assets/15355753/877ec2c3-ffe9-432c-b395-23891cda1a35">

**Comment by ashjbarnes** [comment]
This is related

https://github.com/COSIMA/mom6-regional/blob/7f91d87374768d66943d57e389b2237ec78e80f2/regional_library.py#L715-L717

**Comment by ashjbarnes** [comment]
Fixed - user can now provide a 'positivedown' boolean to define the vertical coordinate direction rather than making (bad) assumptions
